#ifndef __CASKY_VERSION_H
#define __CASKY_VERSION_H

#define CASKY_VERSION_MAJOR 0
#define CASKY_VERSION_MINOR 10
#define CASKY_VERSION_PATCH 0

#define CASKY_VERSION_STRING "0.10.0"
#endif // !__CASKY_VERSION_H
